name = "studychaser-api"
main = "src/worker.js"
compatibility_date = "2026-04-29"

[vars]
FRONTEND_ORIGINS = "https://studychaser.katalinalondono.com,https://www.studychaser.katalinalondono.com"

[[kv_namespaces]]
binding = "STUDYCHASER_KV"
id = "b23be0540649488e9f8f6a76511ad375"
